# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import messenger.proto.messenger_pb2 as messenger__pb2


class MessengerServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
                '/mes_grpc.MessengerServer/SendMessage',
                request_serializer=messenger__pb2.SendRequest.SerializeToString,
                response_deserializer=messenger__pb2.SendResponse.FromString,
                )
        self.ReadMessages = channel.unary_stream(
                '/mes_grpc.MessengerServer/ReadMessages',
                request_serializer=messenger__pb2.ReadRequest.SerializeToString,
                response_deserializer=messenger__pb2.ReadResponse.FromString,
                )


class MessengerServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessengerServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=messenger__pb2.SendRequest.FromString,
                    response_serializer=messenger__pb2.SendResponse.SerializeToString,
            ),
            'ReadMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadMessages,
                    request_deserializer=messenger__pb2.ReadRequest.FromString,
                    response_serializer=messenger__pb2.ReadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mes_grpc.MessengerServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MessengerServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mes_grpc.MessengerServer/SendMessage',
            messenger__pb2.SendRequest.SerializeToString,
            messenger__pb2.SendResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mes_grpc.MessengerServer/ReadMessages',
            messenger__pb2.ReadRequest.SerializeToString,
            messenger__pb2.ReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
